processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "881bL8X9SNvdduRcx2kgMhDdjJ7X9wLiTTJiJeSXAjNs",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "GsijPxkkbmnNVhNTxXn7xst7uDoRvarRQuMRzb4PDqWc",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "881bL8X9SNvdduRcx2kgMhDdjJ7X9wLiTTJiJeSXAjNs",
      "sequenceNumber": 2
    }
  }
}
